language: python
python:
  - "3.6"
  - "3.8"
  - "3.9"
cache: pip
before_install:
  - sudo apt-get -y install gcc gfortran
install:
  - pip install -r requirements.txt
script:
  - python imbot/telegramnote.py
  - python imbot/martas.py
  - python imbot/secondanalysis.py -D
  - python imbot/minuteanalysis.py -D
  - python3 imbot/secondanalysis.py -s test/second/ -d /tmp -t /tmp -q 2021-05-15,2021-05-16 -n /etc/martas/telegram_imbot.cfg -o REFEREE -i test/minute1/ -j test/minute2/ -k test/minute3/ -e config/ -l /tmp -c /etc/martas/mail.cfg -p KOU -y 2021 -w 0 -D
